# Generated by Django 5.2.4 on 2026-04-30 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('home', 'Home Loan'), ('personal', 'Personal Loan'), ('car', 'Car Loan')], max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('married', models.CharField(max_length=5)),
                ('dependents', models.CharField(max_length=5)),
                ('education', models.CharField(max_length=20)),
                ('self_employed', models.CharField(max_length=5)),
                ('applicant_income', models.FloatField()),
                ('coapplicant_income', models.FloatField(default=0)),
                ('loan_amount', models.FloatField()),
                ('loan_amount_term', models.FloatField()),
                ('credit_history', models.CharField(max_length=5)),
                ('property_area', models.CharField(max_length=15)),
                ('result', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10)),
                ('approved_prob', models.FloatField()),
                ('rejected_prob', models.FloatField()),
                ('monthly_emi', models.FloatField(default=0)),
                ('interest_rate', models.FloatField(default=0)),
                ('model_used', models.CharField(default='', max_length=50)),
                ('receipt_id', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
